name: Terraform code pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        run: terraform init

      - name: Validate code
        run: terraform validate

      - name: Plan of action
        run: terraform plan

      - name: Apply changes
        run: terraform apply --auto-approve  
    
